version: "3.1"
services:
  mqtt:
    image: eclipse-mosquitto
    volumes:
      - "${PWD}/mqtt/config:/mosquitto/config"
    ports:
      - "1883:1883"
      - "9001:9001"
  stream:
    build: ./stream/
    depends_on: 
      - mqtt
    volumes:
      - "${PWD}/stream/code:/opt/code"
    stdin_open: true
    tty: true 
